version: '1'

services:

  nginx:
    image: nginx:latest
    container_name: webserver
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - api-1
      - api-2
    ports:
      - "9000:80"

  api-1:
    container_name: api-1
    image: todin13/storage-api:v2
    environment:
      - REDIS_PORT=6379
      - REDIS_HOST=redis
    ports:
      - "9001:8100"

  api-2:
    container_name: api-2
    image: todin13/storage-api:v2
    environment:
      - REDIS_PORT=6379
      - REDIS_HOST=redis
    ports:
      - "9002:8100"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
  
volumes:
  redis-data: